### ISSUE TITLE
[CORE] Translate the entire base site and posts to Spanish

### ISSUE THREAD

**Issue by alsotoes** [opensource-latinamerica/openinframx#4]
Posts should only be merged if they have both languages.

**Comment by ParzivalRealm** [comment]
Hello, I'm new to contributing to Open Source and want to help with this issue. I am thinking on implementing the Multilingual Hugo capabilities and follow the guide from: https://www.regisphilibert.com/blog/2018/08/hugo-multilingual-part-1-managing-content-translation/ that is mentioned on the Hugo docs. Is this solution related to this issue? Idk if it solves the "Posts should only be merged if they have both language" condition though, but it seems that the project doesn't has set the multilingual and that might help with this.

**Comment by alsotoes** [comment]
Hi @ParzivalRealm, we kinda have this implemented [1], but we need more work to set the default site language to Spanish fully =/  Please feel free to look at [2] for the definition.

1. [per file languages](https://www.regisphilibert.com/blog/2018/08/hugo-multilingual-part-1-managing-content-translation/#:~:text=check%20those%20linkings%3A-,By%20Filename,-content/about.md)
2. [languages.yaml](https://github.com/opensource-latinamerica/openinframx/blob/main/config/_default/languages.yaml)

Cheers!

**Comment by ParzivalRealm** [comment]
I sent a merge request with this, but idk what shall i comment here, or if I need to comment something.

**Comment by alsotoes** [comment]
hey, np, I'll link this to the PR. I'm making some changes and kinda completing this issue.
Cheers!
