### ISSUE TITLE
[POST] Add OpenInfra Foundation CoC

### ISSUE THREAD

**Issue by alsotoes** [opensource-latinamerica/openinframx#5]
Save copy in the repo of CoC from [here](https://openinfra.dev/legal/code-of-conduct) and create a link into the site.
Ask to Open Infra foundation if they have a copy/url in Spanish.

ENG: **Important**, the branch '[5-post-add-openinfra-foundation-coc](https://github.com/opensource-latinamerica/openinframx/tree/5-post-add-openinfra-foundation-coc)' will only be merged after the foundation approval.

ESP: **Importante**, el merge del branch '[5-post-add-openinfra-foundation-coc](https://github.com/opensource-latinamerica/openinframx/tree/5-post-add-openinfra-foundation-coc)'  solo se ejecutará después de la aprobación la fundación.

**Comment by alsotoes** [comment]
This should added in the menu one level before the contact link.
OIF doesn't have the CoC in Spanish, I requested them to translate it.

**Comment by alsotoes** [comment]
PR [pull/12](https://github.com/opensource-latinamerica/openinframx/pull/12) added CoC in english, I'll wait until the official response from OI Foundation to close the issue.

**Comment by alsotoes** [comment]
[PR](https://github.com/opensource-latinamerica/openinframx/pull/16) added CoC link to openinfra [Community Code of Conduct](https://openinfra.dev/legal/code-of-conduct)

**Comment by alsotoes** [comment]
Thanks @hspease99 for your help on this matter.  \o/
We (as a community) will work on the translation efforts with i18n team, to make it happen.

**Comment by hspease99** [comment]
Wonderful! Let me know if there is anything else I can help with :)

**Comment by alsotoes** [comment]
Hi @hspease99 ,
the CoC It's now fully translated into Spanish, so the Foundation can review it and propose changes if needed.

The same can be found [here](https://github.com/opensource-latinamerica/openinframx/blob/5-post-add-openinfra-foundation-coc/CODE_OF_CONDUCT.es.md)

Thanks!

**Comment by alsotoes** [comment]
ENG: We need to add the list of translators and reviewers at the end of the file so the Foundation can allow this to serve as official. Sign your commit, please.

ESP: Necesitamos agregar la lista de traductores y revisores al final del archivo para que pueda considerarse como oficial la fundación. Firmen sus commits.

**Comment by alsotoes** [comment]
[ENG] We need more than 3 reviewers to work on making this official.
[ESP] Necesitamos más de 3 revisores para que la traducción sea oficial.

#AskForHelp

**Comment by alsotoes** [comment]
[ENG] Today our translation has been accepted as community official and can now be merged to our main branch \o/
Kudos to all those involved. cc/ @hspease99 
[ESP] Hoy nuestra traducción fue aceptada como oficial para y por la comunidad, ya podemos darle merge \o/
Felicitaciones a todos los involucrados.

![Screenshot from 2024-03-26 17-28-42](https://github.com/opensource-latinamerica/openinframx/assets/758022/574636f7-3e98-49d3-93e5-7639f52c77a0)
